openapi: 3.0.0
x-stoplight:
  id: d9nffhenkve01
info:
  title: ansvar
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /driftsansvar/person:
    post:
      summary: Opprett driftsansvarlig for person
      operationId: post-driftansvarligperson
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Driftsansvarlig.yaml
      x-stoplight:
        id: pntgftk8gjyi2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                foedselsnummer:
                  type: string
                  x-stoplight:
                    id: 2q7lydqztdt6w
              required:
                - foedselsnummer
      description: 'Den som har juridisk ansvar for dyr, ofte eieren, men ikke alltid.'
    parameters: []
  '/driftsansvar/{driftansvarid}/ansvar':
    parameters:
      - schema:
          type: integer
          format: int64
        name: driftansvarid
        in: path
        required: true
    post:
      summary: Opprett Ansvar
      operationId: post-driftsansvarlig-id-ansvar
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Ansvar.yaml
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Ansvar.yaml
      x-stoplight:
        id: wcjwpmzi8daxl
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                organisasjonsnummerUnderenhet:
                  type: string
                  x-stoplight:
                    id: cwjzzy29vahqm
                kategori:
                  $ref: ../models/kodeverk/Kategori.yaml
                ansvarstype:
                  $ref: ../models/kodeverk/Hovedtype.yaml
              required:
                - organisasjonsnummerUnderenhet
            examples:
              Example 1:
                value:
                  organisasjonsnummerUnderenhet: string
                  kategori:
                    dyreholdskategori: FUGLER
                  ansvarstype:
                    hovedtype: DYREHOLD
        description: ''
      description: 'I kontekst av dyrehold er ansvar den dyregruppen du har ansvar for. F.eks storfe, eller fj√∏rfe'
  /driftsansvar/organisasjon:
    post:
      summary: Opprett driftsansvarlig for foretak
      operationId: post-driftsansvarligorg
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Driftsansvarlig.yaml
      x-stoplight:
        id: 0iwuev36xrij9
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                orgnummerHovedenhet:
                  type: string
                  x-stoplight:
                    id: 759ior5z46xcn
              required:
                - orgnummerHovedenhet
      description: 'Den som har juridisk ansvar for dyr, ofte eieren, men ikke alltid.'
    parameters: []
  '/driftsansvar/{driftsansvarid}/kontaktperson':
    parameters:
      - schema:
          type: integer
          format: int64
        name: driftsansvarid
        in: path
        required: true
    post:
      summary: Opprett kontaktperson
      operationId: post-driftsansvarlig-kontaktperson
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Kontaktperson.yaml
      x-stoplight:
        id: 7af52j9zw3pa6
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fornavn:
                  type: string
                  x-stoplight:
                    id: ukrzk6pkdeozu
                etternavn:
                  type: string
                  x-stoplight:
                    id: 2cn4x1e7i66ts
                telefonnummer:
                  type: string
                  x-stoplight:
                    id: 5nwhtwfvuk5q8
                epost:
                  type: string
                  x-stoplight:
                    id: 82h96sayz0fi6
                roller:
                  x-stoplight:
                    id: b5779i6j3oujb
                  type: array
                  items:
                    $ref: ../models/kodeverk/Roller.yaml
              required:
                - fornavn
                - etternavn
                - telefonnummer
                - roller
            examples:
              Example 1:
                value:
                  fornavn: string
                  etternavn: string
                  telefonnummer: string
                  epost: string
                  roller:
                    - roller: EIER
      description: Oppretter kontaktperson for et gitt driftsansvar. F.eks den som kan konktaktes ved tilsyn
  '/driftsansvar/{driftansvarid}/ansvar/{ansvarid}/aktivitet':
    parameters:
      - schema:
          type: integer
          format: int64
        name: driftansvarid
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: ansvarid
        in: path
        required: true
    post:
      summary: Opprett aktivitet
      operationId: post-driftsansvarlig-id-ansvar-id-aktivitet
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  aktivitet:
                    $ref: ../models/Ansvar/Aktivitet.yaml
      x-stoplight:
        id: 8nc4li9ujbmic
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                aktivitetstype:
                  $ref: ../models/kodeverk/Aktivitetstype.yaml
                verdikjede:
                  $ref: ../models/kodeverk/Verdikjede.yaml
                art:
                  $ref: ../models/kodeverk/Art.yaml
                kunnskap:
                  x-stoplight:
                    id: ewp9oj7z1a13x
                  type: array
                  items:
                    $ref: ../models/kodeverk/Kunnskap.yaml
                antallAarErfaring:
                  type: integer
                  x-stoplight:
                    id: 59k5gqtrsqh60
                  format: int32
                kunnskapAnnen:
                  type: string
                  x-stoplight:
                    id: n1i5mq0sm9csw
                kurs:
                  x-stoplight:
                    id: umfs9ypg8bbcp
                  type: array
                  items:
                    $ref: ../models/kodeverk/Kurs.yaml
              required:
                - aktivitetstype
                - verdikjede
                - art
                - antallAarErfaring
            examples:
              Example 1:
                value:
                  aktivitetstype:
                    aktivitetstypeFugler: RUGEEGG
                    aktivitetstypeStorfe: MELKEKYR
                  verdikjede:
                    verdikjedeFugler: KONSUMEGG
                  art:
                    fugleArt: HONS
                  kunnskap:
                    - kunnskap: UTDANNING
                  antallAarErfaring: -2147483648
                  kunnskapAnnen: string
                  kurs:
                    - kurs: FJOERFEPRODUKSJON
      description: Oppretter aktivitet for et ansvar.
  '/driftsansvar/{driftsansvarid}/ansvar/{ansvarid}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: driftsansvarid
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: ansvarid
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Ansvar.yaml
      operationId: get-driftsansvar-driftsansvarid-ansvar-ansvarid
      x-stoplight:
        id: 6rti7091gj4w9
  '/driftsansvar/{driftsansvarid}/ansvar/{ansvarid}/aktivitet/{aktivitetid}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: driftsansvarid
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: ansvarid
        in: path
        required: true
      - schema:
          type: integer
          format: int64
        name: aktivitetid
        in: path
        required: true
    get:
      summary: GET Aktivitet
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Ansvar.yaml
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../models/Ansvar/Aktivitet.yaml
      operationId: get-driftsansvar-driftsansvarid-ansvar-ansvarid
      x-stoplight:
        id: 8zk7ud56oumwt
components:
  schemas: {}
