openapi: 3.0.0
info:
  title: FrontendSupportAPI
  version: '1.0'
  description: Api som understøtter frontend
servers:
  - url: 'http://localhost:3000'
    description: mock
paths:
  /skjemakomponent:
    post:
      summary: Lagrer komponent til angitt eier og skjema
      tags:
        - Skjemakomponent
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
        '400':
          description: Bad Request
      operationId: post-skjemakomponent
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
        description: Sender inn skjemakomponent som skal lagres
    get:
      summary: Henter alle skjemakomponenter
      tags:
        - Skjemakomponent
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
              examples:
                Example 1:
                  value:
                    - id: 4234234
                      eierid: org342434
                      skjemaid: skj3243
                      skjematype: fjørfehold
                      komponent: produksjonsform
                      komponentid: komp2342
                      endretdato: 12.11.2023
                      datajson: '[{"id": 1, "navn": "rugeegg", "verdikjede": "konsumegg", "art": "hons", "kunnskap": {"id": 1, "tekst": "kurs"}]'
      operationId: get-skjemakomponent
  '/skjemakomponent/eier/{eierid}':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        required: true
    get:
      summary: Henter alle komponenter til angitt eier
      tags:
        - Skjemakomponent
      deprecated: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
              examples:
                Example 1:
                  value:
                    - id: 4234234
                      eierid: org342434
                      skjemaid: skj3243
                      skjematype: fjørfehold
                      komponent: produksjonsform
                      komponentid: komp2342
                      endretdato: 12.11.2023
                      datajson: '[{"id": 1, "navn": "rugeegg", "verdikjede": "konsumegg", "art": "hons", "kunnskap": {"id": 1, "tekst": "kurs"}]'
        '404':
          description: Not Found
      operationId: get-skjemakomponent-eier-eierid
      description: 'Henter ut alle komponenter som er reigstrert på denne eieren uavhengig av typeskjema, skjemaid'
    delete:
      summary: Slett eier
      tags:
        - Skjemakomponent
      deprecated: true
      operationId: delete-skjemakomponent-eier-eierid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      description: Sletter alle skjema med tilhørende komponenter som er knyttet til eierid
  '/skjemakomponent/eier':
    post:
      summary: Henter alle komponenter til angitt eier
      tags:
        - Skjemakomponent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eierid:
                  type: string
              required:
                - eierid
            examples:
              Example 1:
                value:
                  eierid: org342434
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
              examples:
                Example 1:
                  value:
                    - id: 4234234
                      eierid: org342434
                      skjemaid: skj3243
                      skjematype: fjørfehold
                      komponent: produksjonsform
                      komponentid: komp2342
                      endretdato: 12.11.2023
                      datajson: '[{"id": 1, "navn": "rugeegg", "verdikjede": "konsumegg", "art": "hons", "kunnskap": {"id": 1, "tekst": "kurs"}]'
        '404':
          description: Not Found
      operationId: post-skjemakomponent-eier
      description: 'Henter ut alle komponenter som er registrert på denne eieren uavhengig av typeskjema, skjemaid'

    delete:
      summary: Slett eier
      tags:
        - Skjemakomponent
      operationId: delete-skjemakomponent-eier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eierid:
                  type: string
              required:
                - eierid
            examples:
              Example 1:
                value:
                  eierid: org342434
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      description: Sletter alle skjema med tilhørende komponenter som er knyttet til eierid
  '/skjemakomponent/eier/{eierid}/skjema/{skjemaid}':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        required: true
      - schema:
          type: string
        name: skjemaid
        in: path
        required: true
    get:
      summary: Henter alle komponenter til angitt skjema
      tags:
        - Skjemakomponent
      deprecated: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
        '404':
          description: Not Found
      operationId: get-skjemakomponent-eier-eierid-skjema-skjemaid
      description: Henter ut alle komponenter som er registrert på angitt eierid og skjemaid
    put:
      summary: Opprett eller oppdater skjema-metadata
      tags:
        - Skjemakomponent
      deprecated: true
      operationId: put-skjemakomponent-eier-eierid-skjema-skjemaid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
      description: 'Oppretter et skjema eller oppdaterer et skjema, ved å lagre en "spesial" komponent angitt av skjematype'
      parameters:
        - schema:
            type: string
          in: query
          name: skjematype
          description: Angir hva slags skjema som lagres
          required: true
    delete:
      summary: Slett ett skjema
      tags:
        - Skjemakomponent
      deprecated: true
      operationId: delete-skjemakomponent-eier-eierid-skjema-skjemaid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      description: Sletter alle komponenter på et skjema
  '/skjemakomponent/skjema/{skjemaid}':
    parameters:
      - name: skjemaid
        in: path
        required: true
        schema:
          type: string

    post:
      summary: Henter alle komponenter til angitt skjema
      tags:
        - Skjemakomponent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eierid:
                  type: string
              required:
                - eierid
            examples:
              Example 1:
                value:
                  eierid: org342434
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
        '404':
          description: Not Found
      operationId: post-skjemakomponent-skjema-skjemaid
      description: Henter ut alle komponenter som er registrert på angitt skjemaid og eierid

    put:
      summary: Opprett eller oppdater skjema-metadata
      tags:
        - Skjemakomponent
      operationId: put-skjemakomponent-skjema-skjemaid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eierid:
                  type: string
                skjematype:
                  type: string
              required:
                - eierid
                - skjematype
            examples:
              Example 1:
                value:
                  eierid: org342434
                  skjematype: fjørfehold
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
      description: Oppretter eller oppdaterer et skjema ved å lagre en spesialkomponent angitt av skjematype

    delete:
      summary: Slett ett skjema
      tags:
        - Skjemakomponent
      operationId: delete-skjemakomponent-skjema-skjemaid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eierid:
                  type: string
              required:
                - eierid
            examples:
              Example 1:
                value:
                  eierid: org342434
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      description: Sletter alle komponenter på et skjema for gitt eier
  '/skjemakomponent/eier/{eierid}/skjema/{skjemaid}/komponent/{komponentblokk}':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        required: true
      - schema:
          type: string
        name: skjemaid
        in: path
        required: true
      - schema:
          type: string
        name: komponentblokk
        in: path
        required: true
    get:
      summary: Henter alle komponenter til angitt komponentblokk
      tags:
        - Skjemakomponent
      deprecated: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
              examples:
                Example 1:
                  value:
                    - id: 4234234
                      eierid: org342434
                      skjemaid: skj3243
                      skjematype: fjørfehold
                      komponent: produksjonsform
                      komponentid: komp2342
                      endretdato: 12.11.2023
                      datajson: '[{"id": 1, "navn": "rugeegg", "verdikjede": "konsumegg", "art": "hons", "kunnskap": {"id": 1, "tekst": "kurs"}]'
        '404':
          description: Not Found
      operationId: get-skjemakomponent-eier-eierid-skjema-skjemaid-komponent-komponentblokk
      description: 'Henter ut komponenten som er registrert på angitt eierid,skjemaid og komponentblokk. Komponentblokk er taggen som json strukturen til komponenten ligger under. I dette tilfellet er id = komponentblokk'
    put:
      summary: Opprett eller oppdater en skjemakomponent
      tags:
        - Skjemakomponent
      deprecated: true
      operationId: put-skjemakomponent-eier-eierid-skjema-skjemaid-komponent-komponentblokk
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
      description: 'Lager en komponenten som er registrert på angitt eierid,skjemaid og komponentblokk. Komponentblokk er taggen som json strukturen til komponenten ligger under. I dette tilfellet er id = komponentblokk'
      requestBody:
        content:
          application/json:
            schema:
              type: string
        description: ''
    delete:
      summary: Slett komponent blokk
      tags:
        - Skjemakomponent
      deprecated: true
      operationId: delete-skjemakomponent-eier-eierid-skjema-skjemaid-komponent-komponentblokk
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      description: Sletter en komponentblokk
  '/skjemakomponent/skjema/{skjemaid}/komponent/{komponentblokk}':
    parameters:
      - name: skjemaid
        in: path
        required: true
        schema:
          type: string
      - name: komponentblokk
        in: path
        required: true
        schema:
          type: string

    post:
      summary: Henter alle komponenter til angitt komponentblokk
      tags:
        - Skjemakomponent
      operationId: post-skjemakomponent-skjema-skjemaid-komponent-komponentblokk
      description: >
        Henter ut komponentene som er registrert på angitt `skjemaid` og `komponentblokk` for en spesifikk `eierid`.  
        `komponentblokk` er navnet på feltet i JSON-strukturen som brukes som tag/id.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eierid:
                  type: string
              required:
                - eierid
            examples:
              Example 1:
                value:
                  eierid: org342434
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
              examples:
                Example 1:
                  value:
                    - id: 4234234
                      eierid: org342434
                      skjemaid: skj3243
                      skjematype: fjørfehold
                      komponent: produksjonsform
                      komponentid: komp2342
                      endretdato: 12.11.2023
                      datajson: '[{"id": 1, "navn": "rugeegg", "verdikjede": "konsumegg", "art": "hons", "kunnskap": {"id": 1, "tekst": "kurs"}]'
        '404':
          description: Not Found

    put:
      summary: Opprett eller oppdater en skjemakomponent
      tags:
        - Skjemakomponent
      operationId: put-skjemakomponent-skjema-skjemaid-komponent-komponentblokk
      description: >
        Lager eller oppdaterer komponenten som tilhører `eierid`, `skjemaid`, og `komponentblokk`.  
        `komponentblokk` angir hvilken del av JSON-strukturen som lagres.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eierid:
                  type: string
                body:
                  type: string
              required:
                - eierid
                - body
            examples:
              Example 1:
                value:
                  eierid: org342434
                  data:
                    skjematype: fjørfehold
                    komponent: produksjonsform
                    komponentid: komp2342
                    datajson: '[{"id":1,"navn":"rugeegg","art":"hons"}]'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml

    delete:
      summary: Slett komponentblokk
      tags:
        - Skjemakomponent
      operationId: delete-skjemakomponent-skjema-skjemaid-komponent-komponentblokk
      description: >
        Sletter en komponentblokk for en gitt `eierid`, `skjemaid` og `komponentblokk`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eierid:
                  type: string
              required:
                - eierid
            examples:
              Example 1:
                value:
                  eierid: org342434
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  '/skjemakomponent/eier/{eierid}/skjema/{skjemaid}/komponent/{komponentblokk}/id/{id}':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        required: true
      - schema:
          type: string
        name: skjemaid
        in: path
        required: true
      - schema:
          type: string
        name: komponentblokk
        in: path
        required: true
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Henter alle en komponent med id av type komponentblokk
      tags:
        - Skjemakomponent
      deprecated: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
              examples:
                Example 1:
                  value:
                    - id: 4234234
                      eierid: org342434
                      skjemaid: skj3243
                      skjematype: fjørfehold
                      komponent: produksjonsform
                      komponentid: komp2342
                      endretdato: 12.11.2023
                      datajson: '[{"id": 1, "navn": "rugeegg", "verdikjede": "konsumegg", "art": "hons", "kunnskap": {"id": 1, "tekst": "kurs"}]'
        '404':
          description: Not Found
      operationId: get-skjemakomponent-eier-eierid-skjema-skjemaid-komponent-komponentblokk-id-id
      description: 'Henter ut komponent av en gitt type som er registrert på angitt eierid,skjemaid og komponentblokk og id. Når du bruker dette endepunktet så er komponentblokk en slags kategori av komponenter. id er taggen som json strukturen til komponenten ligger under.'
    put:
      summary: Opprett eller oppdater en skjemakomponent
      tags:
        - Skjemakomponent
      deprecated: true
      operationId: put-skjemakomponent-eier-eierid-skjema-skjemaid-komponent-komponentblokk-id-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
      description: 'Lagrer en komponent av en gitt type som er registrert på angitt eierid,skjemaid og komponentblokk og id. Når du bruker dette endepunktet så er komponentblokk en slags kategori av komponenter. id er taggen som json strukturen til komponenten ligger under.'
      requestBody:
        content:
          application/json:
            schema:
              type: string
        description: ''
    delete:
      summary: Slett komponent blokk
      tags:
        - Skjemakomponent
      deprecated: true
      operationId: delete-skjemakomponent-eier-eierid-skjema-skjemaid-komponent-komponentblokk-id-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      description: Sletter en komponent under en kompnentblokk
  '/skjemakomponent/skjema/{skjemaid}/komponent/{komponentblokk}/id/{id}':
    parameters:
      - name: skjemaid
        in: path
        required: true
        schema:
          type: string
      - name: komponentblokk
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string

    post:
      summary: Henter én komponent med angitt id innenfor en komponentblokk
      tags:
        - Skjemakomponent
      operationId: post-skjemakomponent-skjema-skjemaid-komponent-komponentblokk-id-id
      description: >
        Henter en komponent registrert på gitt `skjemaid`, `komponentblokk` og `id` for en spesifikk `eierid`.  
        `komponentblokk` representerer en kategori, og `id` er taggen i JSON-strukturen.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eierid:
                  type: string
              required:
                - eierid
            examples:
              Example 1:
                value:
                  eierid: org342434
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml
              examples:
                Example 1:
                  value:
                    - id: 4234234
                      eierid: org342434
                      skjemaid: skj3243
                      skjematype: fjørfehold
                      komponent: produksjonsform
                      komponentid: komp2342
                      endretdato: 12.11.2023
                      datajson: '[{"id":1,"navn":"rugeegg","art":"hons"}]'
        '404':
          description: Not Found

    put:
      summary: Opprett eller oppdater en skjemakomponent
      tags:
        - Skjemakomponent
      operationId: put-skjemakomponent-skjema-skjemaid-komponent-komponentblokk-id-id
      description: >
        Lagrer eller oppdaterer en komponent under gitt `komponentblokk` med identifikator `id`, knyttet til `skjemaid` og `eierid`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eierid:
                  type: string
                body:
                  type: string
              required:
                - eierid
                - body
            examples:
              Example 1:
                value:
                  eierid: org342434
                  data:
                    komponent: produksjonsform
                    komponentid: komp2342
                    skjematype: fjørfehold
                    datajson: '[{"id":1,"navn":"rugeegg"}]'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Skjemakomponent/SkjemaKomponent.yaml

    delete:
      summary: Slett komponent under komponentblokk
      tags:
        - Skjemakomponent
      operationId: delete-skjemakomponent-skjema-skjemaid-komponent-komponentblokk-id-id
      description: >
        Sletter én komponent under `komponentblokk` for en spesifikk `skjemaid`, `id` og `eierid`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eierid:
                  type: string
              required:
                - eierid
            examples:
              Example 1:
                value:
                  eierid: org342434
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string

  '/skjemakomponent/eier/{eier}/skjema':
    parameters:
      - schema:
          type: string
        name: eier
        in: path
        required: true
    get:
      summary: Hent alle skjema-metadata for eier
      tags:
        - Skjemakomponent
      deprecated: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaMetadata.yaml
      operationId: get-skjemakomponent-eier-eier-skjema
      description: 'Henter ut liste med alle skjema på en eier, evt. filtrert på skjematype'
      parameters:
        - schema:
            type: string
          in: query
          name: skjematype
          description: angi en skjematype
  '/skjemakomponent/skjema':
    post:
      summary: Hent alle skjema-metadata for eier
      tags:
        - Skjemakomponent
      operationId: post-skjemakomponent-skjema
      description: >
        Henter ut liste med alle skjema tilhørende en eier.  
        Kan filtreres på `skjematype` via query-param.
      parameters:
        - name: skjematype
          in: query
          description: Angi en skjematype for filtrering
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eier:
                  type: string
              required:
                - eier
            examples:
              Example 1:
                value:
                  eier: org342434
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaMetadata.yaml

  '/skjemakomponent/godkjenteier/eier/{eierid}/orgnummer/{orgnummer}/skjema':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        required: true
      - schema:
           type: string
        name: orgnummer
        in: path
        required: true
    get:
      summary: Hent alle skjema-metadata for orgnummer hvor det finnes et eksisterende anlegg med status GODKJENT_EIER
      tags:
        - Skjemakomponent
      deprecated: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaMetadata.yaml
      operationId: get-skjemakomponent-godkjenteier-eier-eierid-orgnummer-orgnummer-skjema
      description: 'Henter ut liste med alle skjema gitt en  organisasjon, evt. filtrert på skjematype og status GODKJENT_EIER'
      parameters:
        - schema:
            type: string
          in: query
          name: skjematype
          description: angi en skjematype
  '/skjemakomponent/godkjenteier/skjema':
    post:
      summary: Hent alle skjema-metadata for orgnummer med status GODKJENT_EIER
      tags:
        - Skjemakomponent
      operationId: post-skjemakomponent-godkjenteier-skjema
      description: >
        Henter alle skjema tilhørende `orgnummer` og `eierid` hvor det finnes et anlegg med status GODKJENT_EIER.
        Kan filtreres på `skjematype`.
      parameters:
        - name: skjematype
          in: query
          schema:
            type: string
          description: Angi en skjematype
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eierid:
                  type: string
                orgnummer:
                  type: string
              required:
                - eierid
                - orgnummer
            examples:
              Example 1:
                value:
                  eierid: org342434
                  orgnummer: 123456789
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaMetadata.yaml
  '/skjemakomponent/ikkegodkjenteier/eier/{eierid}/orgnummer/{orgnummer}/skjema':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        required: true
      - schema:
          type: string
        name: orgnummer
        in: path
        required: true
    get:
      summary: Hent alle skjema-metadata for orgnummer hvor det finnes et eksisterende anlegg og status ikke er GODKJENT_EIER
      tags:
        - Skjemakomponent
      deprecated: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaMetadata.yaml
      operationId: get-skjemakomponent-ikkegodkjenteier-eier-eierid-orgnummer-orgnummer-skjema
      description: 'Henter ut liste med alle skjema gitt en  organisasjon, evt. filtrert på skjematype  hvor status ikke er GODKJENT_EIER'
      parameters:
        - schema:
            type: string
          in: query
          name: skjematype
          description: angi en skjematype
  '/skjemakomponent/ikkegodkjenteier/skjema':
    post:
      summary: Hent alle skjema-metadata for orgnummer hvor status IKKE er GODKJENT_EIER
      tags:
        - Skjemakomponent
      operationId: post-skjemakomponent-ikkegodkjenteier-skjema
      description: >
        Henter alle skjema tilhørende `orgnummer` og `eierid` hvor det finnes et anlegg og status ikke er GODKJENT_EIER.
        Kan filtreres på `skjematype`.
      parameters:
        - name: skjematype
          in: query
          schema:
            type: string
          description: Angi en skjematype
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eierid:
                  type: string
                orgnummer:
                  type: string
              required:
                - eierid
                - orgnummer
            examples:
              Example 1:
                value:
                  eierid: org342434
                  orgnummer: 987654321
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaMetadata.yaml

  '/skjemakomponent/eier/{eierid}/orgnummer/{orgnummer}/skjema':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        required: true
      - schema:
          type: string
        name: orgnummer
        in: path
        required: true
    get:
      summary: Hent alle skjema-metadata for orgnummer hvor det finnes et eksisterende anlegg
      tags:
        - Skjemakomponent
      deprecated: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaMetadata.yaml
      operationId: get-skjemakomponent-eier-eier-orgnummer-orgnummer-skjema
      description: 'Henter ut liste med alle skjema gitt en  organisasjon, evt. filtrert på skjematype'
      parameters:
        - schema:
            type: string
          in: query
          name: skjematype
          description: angi en skjematype
  '/skjemakomponent/orgnummer/{orgnummer}/skjema':
    parameters:
      - name: orgnummer
        in: path
        required: true
        schema:
          type: string
    post:
      summary: Hent alle skjema-metadata for orgnummer hvor det finnes et eksisterende anlegg
      tags:
        - Skjemakomponent
      operationId: post-skjemakomponent-eier-orgnummer-skjema
      description: >
        Henter ut liste med alle skjema gitt en organisasjon (orgnummer) og eierid i body,
        evt. filtrert på skjematype.
      parameters:
        - name: skjematype
          in: query
          schema:
            type: string
          description: angi en skjematype
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eierid:
                  type: string
              required:
                - eierid
            examples:
              example-1:
                value:
                  eierid: org342434
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Skjemakomponent/SkjemaMetadata.yaml



  '/skjemakomponent/eier/{eierid}/skjema/{skjemaid}/komponent/{komponentblokk}/data':
    parameters:
      - schema:
          type: string
        name: eierid
        in: path
        required: true
      - schema:
          type: string
        name: skjemaid
        in: path
        required: true
      - schema:
          type: string
        name: komponentblokk
        in: path
        required: true
    get:
      summary: Henter kun datajson fra en komponentblokk
      tags:
        - Skjemakomponent
      deprecated: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      operationId: get-skjemakomponent-eier-eierid-skjema-skjemaid-komponent-komponentblokk-data
      description: Brukes dersom man har stål kontroll på metadata og bare vil ha innholdet i en gitt komponent
  '/skjemakomponent/skjema/{skjemaid}/komponent/{komponentblokk}/data':
    parameters:
      - name: skjemaid
        in: path
        required: true
        schema:
          type: string
      - name: komponentblokk
        in: path
        required: true
        schema:
          type: string
    post:
      summary: Henter kun datajson fra en komponentblokk
      tags:
        - Skjemakomponent
      operationId: post-skjemakomponent-eierid-skjema-skjemaid-komponent-komponentblokk-data
      description: >
        Brukes dersom man har stål kontroll på metadata og bare vil ha innholdet i en gitt komponent.
        Eierid sendes i body.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eierid:
                  type: string
              required:
                - eierid
            examples:
              example-1:
                value:
                  eierid: org342434
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string

components:
  schemas: {}
tags:
  - name: Skjemakomponent
